"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[](#A3BE8C)\
[](bg:#5E81AC fg:#A3BE8C)\
$directory\
[](fg:#5E81AC bg:#A3BE8C)\
$git_branch\
$git_status\
[ ](fg:#A3BE8C bg:transparent)\
"""


[directory]
style = "fg:#2E3440 bg:#5E81AC"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
# "Desktop" = "󰟀 "

[git_branch]
symbol = ""
style = "fg:#2E3440 bg:#A3BE8C"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#2E3440 bg:#A3BE8C"
format = '[$all_status$ahead_behind ]($style)'

[username]
disabled = true

[hostname]
disabled = true

[os]
disabled = true

[time]
disabled = true

[character]
disabled = true