# Fast, clean macOS Zsh setup

# PATH
export PATH="$HOME/bin:$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"
export PATH="$HOME/.antigravity-ide/antigravity-ide/bin:$PATH"

DEFAULT_USER=$(whoami)

# Completions
fpath=(
  /opt/homebrew/share/zsh/site-functions
  $fpath
)

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'm:{A-Z}={a-z}'
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' use-cache yes
zstyle ':completion:*' cache-path ~/.zsh/cache

setopt AUTO_CD
setopt EXTENDED_GLOB

HISTSIZE=50000
SAVEHIST=50000
HISTFILE=~/.zsh_history

setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt SHARE_HISTORY



autoload -Uz compinit
compinit -C


# Antidote plugins

source "$(brew --prefix)/opt/antidote/share/antidote/antidote.zsh"

if [[ ! -f ~/.zsh_plugins.zsh || ~/.zsh_plugins.txt -nt ~/.zsh_plugins.zsh ]]; then
  antidote bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.zsh
fi

source ~/.zsh_plugins.zsh


eval "$(zoxide init zsh)"


if [[ "$TERM_PROGRAM" != "Apple_Terminal" ]]; then
    eval "$(starship init zsh)"
fi

if [[ "$TERM_PROGRAM" != "vscode" ]]; then
    eval "$(starship init zsh)"
fi



# fzf
source <(fzf --zsh)

# ls / eza
alias ls='eza'
alias l='eza -lah'
alias la='eza -lAh'
alias ll='eza -lah --icons --git --group-directories-first'
alias lt='eza -lah --icons --git --sort=modified --group-directories-first'
alias tree='eza -T --icons --git'
alias tree1='eza -T --icons --git --level=1'
alias tree2='eza -T --icons --git --level=2'
alias tree3='eza -T --icons --git --level=3'

# directories
alias c='z'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias -- -='cd -'

# git
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gba='git branch --all'
alias gc='git commit'
alias gca='git commit --all'
alias gcam='git commit --all --message'
alias gcm='git commit --message'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gd='git diff'
alias gl='git pull'
alias gp='git push'
alias gst='git status'
alias gss='git status --short'
alias glog='git log --oneline --decorate --graph'
alias gm='git merge'
alias gr='git remote'
alias grv='git remote --verbose'
alias grb='git rebase'
alias gsta='git stash push'
alias gstp='git stash pop'

# brew
alias brews='brew list'
alias bubu='brew update && brew upgrade'
alias bcbc='brew cleanup --prune=all'

# file handling
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias zshrc='${=EDITOR} ~/.zshrc'
alias dud='du -d 1 -h'
command -v duf >/dev/null 2>&1 || alias duf='du -sh'
alias t='tail -f'

# other aliases
alias h='history'
alias hgrep='fc -El 0 | grep'
alias help='man'
alias p='ps -f'

# environment variables
export HOMEBREW_NO_ASK=1
export EDITOR="code --wait"
